### PR TITLE
Adding Onboarding Basics

### PR DESCRIPTION
**Pull request by trunci**
## About this PR

Adding the functionality to show screens for onboarding

## To-dos

* Add the initial questions
* Open screen upon startup

## Testing

localhost_55348_ (3)
localhost_55348_ (2)
localhost_55348_ (1)
localhost_55348_

### CODE REVIEW

**Comment by DanielYoung09** [comment]
Very cool, thank you and gj!
I do see an error in the console that I haven't seen up until this point - 
image
May be related to Recommendations, which is not functioning in this build.

**Review by ShenY11 — COMMENTED** [review]
Looks goo to me! Though one thing is that would black row on the bottom be too dark and kinda passive? Probably a lighter one would be great.

**Review by suvanadhikari — APPROVED** [review]
LGTM!

**Comment by trunci** [comment]
Thanks for the idea! @ShenY11 here is the new version:

image

**Comment by trunci** [comment]
Talked offline to @DanielYoung09; this error doesn't cause anything. Will look for a way to remove it in the future.

**Pull request merged**
