### PR TITLE
Relief Technique Update

### PR DESCRIPTION
**Pull request by DanielYoung09**
Updated Relief Techniques with results of community survey. RIP 'Play Volleyball'
image

### CODE REVIEW

**Comment by DanielYoung09** [comment]
@trunci new bug: this happened after completing onboarding
image

**Comment by DanielYoung09** [comment]
image

**Comment by DanielYoung09** [comment]
Removed debug flags.
image

**Comment by DanielYoung09** [comment]
Corrected overflow.
image

**Comment by trunci** [comment]
@DanielYoung09 did you fix the bug you pointed out?

**Comment by DanielYoung09** [comment]
@trunci No, I didn't. I wanted to alert you because it seems related to onboarding or the new top bars.

**Comment by trunci** [comment]
@DanielYoung09 okay. I'll fix it when you merge this PR. Thanks!

**Pull request merged**
