### PR TITLE
Relief Technique Performance Restyled

### PR DESCRIPTION
**Pull request by AlexShor0103**
### Main Feature:
- This is a small pr where I just changed some of the stylings of the relief technique performance screen
image

### Bugs:
- No currently Noticeable Bugs

### Future Steps:
- Fix Rating Screen
- Make Background Colors consistent

### Minor Concerns:
- This is minor, but should the "non-button" text be the purple or the black? and same question applies to button

### CODE REVIEW

**Review by DanielYoung09 — COMMENTED** [review]
To answer your question - I would like to see it with the purple. Is that something you could get us a screenshot of real quick just to compare? :)

**Review by trunci — CHANGES_REQUESTED** [review]
Waiting for the screenshot requested by Daniel

**Comment by AlexShor0103** [comment]
Here's both purple: 
image

And here's non-button text purple and button text black: 
image

**Comment by DanielYoung09** [comment]
I really like the purple! Both purple would be my personal recommendation, but I'll defer to the group's decision.

**Review by DanielYoung09 — APPROVED** [review]
All clear!

**Review by trunci — APPROVED** [review]
Great! Fix merge conflicts and feel free to merge.

**Pull request merged**
