### PR TITLE
Recommendation links

### PR DESCRIPTION
**Pull request by DanielYoung09**
So it turns out that opening links wasn't an implementation error or bug, but a way in which our emulators have to be set up. We did have a single link implemented, however, which has now been updated so that all recommendations go to their respective store pages.

To allow your emulator to open links to the store:
1) Pull down the window until you find the settings cog.
3) Apps & notifications
2) Advanced - Default apps
3) Make sure Browser app -> Make sure Chrome is selected.
4) Back to apps & notifications -> 'see all apps' near the top. Find 'Google Play Store'
5) Advanced - Open by default
6) Open supported links -> Ask every time.
7) Go to emulator home screen and open Chrome. Follow instructions until you get to the Google home page.
8) Double check that the settings were saved - my emulator removed them and I had to set them a second time.

Additionally, it seems that not all emulators will work correctly - I have this working on Pixel 3 API 30, but the links will not open on Nexus 6 API 33. If you succeed or fail in opening the links, please note which emulator you are using. Thanks!

image
image

### CODE REVIEW

**Comment by trunci** [comment]
@DanielYoung09 the fact that it doesn't work on the web is intentional or not?

**Comment by DanielYoung09** [comment]
@trunci Intended in the sense that I was specifically building for mobile.

**Comment by DanielYoung09** [comment]
@trunci current state: working for web _or_ mobile but not both

**Comment by DanielYoung09** [comment]
Newest commit should do it, give it a look on web 
image

**Review by trunci — APPROVED** [review]
Great; thanks for addressing my comments

**Pull request merged**
