### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by trunci**
## Bug Fixes

1. Added the proper headers to each one of the pages
2. Fixed navigation with the crisis screen
3. Fixed some text overflows

## Testing
[screen-capture (3).webm](https://user-images.githubusercontent.com/26496730/205451258-b5a71654-b23a-41ae-ab68-7d8a06a796d2.webm)

### CODE REVIEW

**Review by DanielYoung09 — APPROVED** [review]
Solid. Branching from this to include emergency call button updates.

**Review by AlexShor0103 — APPROVED** [review]
Looks good to me!

**Review by ShenY11 — COMMENTED** [review]
I still see some overflows when running the app on a iPhone 14 pro simulator.

Screenshot 2022-12-03 at 15 17 17
Screenshot 2022-12-03 at 15 16 15

**Comment by trunci** [comment]
@ShenY11 can you test it again now? Thanks!

**Comment by ShenY11** [comment]
The nav bar looks great now and no overflow, but the contacts screen throws an exception.
Screenshot 2022-12-03 at 15 35 48
Screenshot 2022-12-03 at 15 36 14

**Comment by trunci** [comment]
Do you mind sharing more detail on the error? I couldn't reproduce and the screenshot is not related to the Contacts screen. @ShenY11

**Comment by ShenY11** [comment]
My bad for not being clear. The error raised in the contactsScreen is shown in the first screenshot, but I cannot see the issue either. And the overflow is in the crisis plan as shown in the second screenshot.

**Comment by trunci** [comment]
Great. Then this issue is fixed. Can you ping @DanielYoung09 about the overflow? I am not working on that screen. @ShenY11

**Comment by DanielYoung09** [comment]
I'm getting the error that Jess pointed out on contacts: 
image

**Pull request merged**
