### PR TITLE
Add WarningSigns Autocomplete

### PR DESCRIPTION
**Pull request by AlexShor0103**
### MAIN FEATURES:
- Added Warning Signs list
image

- Implemented Autocomplete for Warning Signs
image
- that changes depending on amount of options
image

### BUGSn
- Not sure if the current version is linked to the backend properly

### CODE REVIEW

**Review by DanielYoung09 — COMMENTED** [review]
Cool addition! I did find this bug. We would expect 'paranoia' to be included
image

Depending on how much more you have today, I would say this is probably fine. We can add this as a known issue.

**Comment by AlexShor0103** [comment]
I'm trying to get as much of my stuff done as possible first, and then going back for bugs, so I would greatly appreciate adding that as a known issue, Thank you for letting me know.

**Comment by trunci** [comment]
@AlexShor0103 I disagree with you on the last comment directed at Daniel; this feature is not working if that is not fixed. That is not a bug, is a faulty feature.

**Review by trunci — CHANGES_REQUESTED** [review]
I'd suggest fixing Daniel's comment.

**Comment by AlexShor0103** [comment]
@trunci we ended up fixing it! Sorry, I don't believe I updated the pr comment to reflect that

**Comment by trunci** [comment]
Please update the PR and I'll be happy to approve it.

**Review by trunci — APPROVED** [review]
Great!

**Pull request merged**
