### PR TITLE
Reskin Crisis Plan

### PR DESCRIPTION
**Pull request by AlexShor0103**
### Main Features
- Cosmetic Reskinning of Crisis Plan
image
image

### Known Bugs
- Nav Bar Not Showing Up
- Not so much a bug as a cosmetic artifact, but presence of inconsistent placeholder text (or lack thereof such as on Distracting Contact 2). This will go away as we begin to make relevant updates to crisis plan

### Of note
- I've created a folder called Crisis Plan in which I plan on storing relevant components for the Crisis Plan screen, but which is currently unused
### Next Steps
- Implement auto complete for relevant text fields
- Implement relief technique, contact buttons
- implement individual card editing

### CODE REVIEW

**Comment by trunci** [comment]
@AlexShor0103 what is this rectangle that appears to the right of some text inputs?

**Comment by AlexShor0103** [comment]
I believe that's an artifact due to text overflow from the existing hint text

**Review by DanielYoung09 — COMMENTED** [review]
Looks good. Bottommost card has pixel overflow issue that relief cards have. We also might move the top card down a little bit so it's not impinging on the top of the screen. I may just grab that when I give contacts phone #s.

**Review by trunci — CHANGES_REQUESTED** [review]
Please fix the leading rectangles in the input text field!

**Review by ShenY11 — APPROVED** [review]
Looks good to me!

**Comment by AlexShor0103** [comment]
Here's an update that fixes the text overflow on the crisis plan cards, and adds a bit more room to the top and bottom of the list
image
image

**Review by trunci — APPROVED** [review]
LGTM

**Pull request merged**
